### CONSTANTS ####

# colours
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
LIGHT_RED = (150, 20, 20)
GREEN = (0, 255, 0)
GREY = (128, 128, 128)
YELLOW = (255, 255, 0)
LIGHT_GREY = (211, 211, 211)
DARK_GREEN = (1, 50, 32)
LIGHT_GREEN = (144, 238, 144)
PURPLE = (128, 0, 128)
PINK = (255, 192, 203)

# Display constants
GRID_SIZE = 20
NODE_SIZE = 19
ROWS = 60
COLS = 60
FPS = 60
BARRIER_CHANCE = 0.3

# section sizes
EXTRA_WIDTH_PX = 200
WIDTH_OFFSET_PX = 50
HEIGHT_OFFSET_PX = 50
PADDING_PX = 40
BUTTON_PADDING = 40
ACTUAL_WIDTH = COLS * GRID_SIZE + 2*WIDTH_OFFSET_PX + EXTRA_WIDTH_PX + PADDING_PX
ACTUAL_HEIGHT = ROWS * GRID_SIZE + 2*HEIGHT_OFFSET_PX
GRID_ACTUAL_WIDTH = COLS * GRID_SIZE
GRID_ACTUAL_HEIGHT = ROWS * GRID_SIZE

# Button constants
BUTTON_HEIGHT = 60
BUTTON_WIDTH = EXTRA_WIDTH_PX
BUTTON_X = ACTUAL_WIDTH - (EXTRA_WIDTH_PX + PADDING_PX)
FIRST_BUTTON_Y = HEIGHT_OFFSET_PX
SECOND_BUTTON_Y = FIRST_BUTTON_Y + BUTTON_HEIGHT + BUTTON_PADDING
THIRD_BUTTON_Y = SECOND_BUTTON_Y + BUTTON_HEIGHT + BUTTON_PADDING

EXIT_BUTTON_Y = ACTUAL_HEIGHT - HEIGHT_OFFSET_PX - BUTTON_HEIGHT
REGEN_BUTTON_Y = EXIT_BUTTON_Y - BUTTON_HEIGHT - BUTTON_PADDING
RESET_BUTTON_Y = REGEN_BUTTON_Y - BUTTON_HEIGHT - BUTTON_PADDING
